definitions:
  jwtmodel.UserClaims:
    properties:
      id:
        type: integer
      iss:
        type: string
      realm:
        type: string
      roles:
        items:
          type: object
        type: array
      sub:
        type: string
    type: object
  models.Applicant:
    properties:
      applicant_address:
        type: string
      applicant_birth:
        type: string
      applicant_contact:
        type: string
      applicant_id:
        type: string
      applicant_name:
        type: string
      applicant_nationality:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
  models.Employer:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      employer_address:
        type: string
      employer_contact:
        type: string
      employer_faren:
        type: string
      employer_name:
        type: string
      employer_uscc:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
  models.User:
    properties:
      active:
        type: boolean
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      email_checked:
        type: boolean
      id:
        type: integer
      last_login:
        type: string
      phone:
        type: string
      phone_checked:
        type: boolean
      updated_at:
        type: string
      user_type:
        type: integer
      username:
        type: string
    type: object
  models.UserProfile:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
    type: object
  vo.CaseFirstSubmitForm:
    properties:
      applicant:
        $ref: '#/definitions/models.Applicant'
        description: 1.申请人
        type: object
      category_id:
        description: 类型id
        type: integer
      content:
        description: 4.调解事项所依据的事实与理由
        type: string
      form_id:
        description: 5.劳动者填写的表单 id
        type: integer
      materials:
        description: 6. 证据材料 各种id
        items:
          type: integer
        type: array
      respondent:
        $ref: '#/definitions/models.Employer'
        description: 2.被申请人
        type: object
      title:
        description: 3.调解事项
        type: string
    required:
    - applicant
    - content
    - form_id
    - respondent
    - title
    type: object
  vo.Common:
    properties:
      message:
        example: unauthorized
        type: string
      status:
        example: 401
        type: integer
      timestamp:
        example: "2048-05-06 12:34:56"
        type: string
    type: object
  vo.CommonData:
    properties:
      data:
        type: object
      message:
        example: unauthorized
        type: string
      status:
        example: 401
        type: integer
      timestamp:
        example: "2048-05-06 12:34:56"
        type: string
    type: object
  vo.LaborArbitrationForm:
    properties:
      arbitration_time:
        description: 28. 申请仲裁时间年月日
        type: string
      before_sever_labor_relationship_avg_wage:
        description: 20. 双方解除或终止劳动关系前12个月劳动者月平均工资额
        example: 1
        type: number
      before_sever_labor_relationship_range:
        items:
          type: string
        type: array
      contract_wage:
        description: |-
          8. 劳动合同约定的月工资数、工资构成、工时制
          8.1 劳动合同约定的月工资数
        type: number
      contract_wage_component:
        description: 8.2 劳动合同约定的工资构成
        type: string
      contract_wage_type:
        description: 8.3 工时制
        type: integer
      disability_rating_time:
        description: |-
          15. 伤残等级鉴定时间及结果
          15.1 伤残等级鉴定时间
        type: string
      disable_results:
        description: 15.2 伤残等级鉴定结果
        type: integer
      employer_time:
        description: 16.2 用人单位
        example: 1
        type: number
      hire_date:
        description: 2. 入职时间
        type: string
      hospitalization_time:
        description: 14. 住院起止时间
        items:
          type: string
        type: array
      industrial_injury:
        description: 13.2 是否经过工伤认定
        type: boolean
      injury_time:
        description: |-
          13. 发生工伤时间、工伤认定情况
          13.1 发生工伤时间
        type: string
      involve_group:
        description: 29. 涉及群体性是□否□
        type: boolean
      job_name:
        description: 6. 劳动合同约定的工作岗位
        type: string
      job_work_place:
        description: 7. 劳动合同约定的工作地点
        type: string
      labor_contract:
        items:
          type: string
        type: array
      labor_contract_completed:
        description: 27. 已办理劳动合同解除手续
        type: boolean
      labor_contract_not_signed:
        description: 5. 未签书面劳动合同工作期间
        items:
          type: string
        type: array
      labor_contract_signed:
        description: 3.1 是否签订书面劳动合同
        type: boolean
      labor_contract_signing_date:
        description: 3.2 签订时间
        type: string
      labor_contract_type:
        description: 4.劳动合同起止时间
        type: integer
      laborer_time:
        description: |-
          16. 停工留薪期限时间  //格式都不对
          16.1 劳动者
        example: 1
        type: number
      last_payment:
        description: 10. 最后一次支付工资时间
        example: 2010-01
        type: string
      main:
        description: 1. 主体性质
        type: integer
      no_overtime_avg_wage:
        description: 23. 扣除加班工资后十二个月劳动者月平均工资数额
        example: 1
        type: number
      no_overtime_avg_wage_range:
        items:
          type: string
        type: array
      normal_overtime:
        description: 18. 加班时间
        example: 10
        type: number
      not_take_days:
        description: 未休
        type: integer
      number:
        description: 3.3 签订次数
        type: integer
      other_information:
        description: 30. 本表遗漏的其他项目
        type: string
      overtime_bonus:
        description: 11.2 欠发加班费奖金
        type: number
      overtime_wage_base:
        description: 19. 加班工资计算基数
        example: 2
        type: number
      paid_annual_leave_not_leave_day:
        description: 22. 未休带薪年休假天数
        type: boolean
      parties_dispute_time:
        description: 24.双方发生劳动争议时间
        example: "2020-01-02"
        type: string
      payment_cycle:
        description: 9.4 发放周期
        type: integer
      payment_type:
        description: 9.3 发放形式
        type: integer
      real_rest:
        description: 实休
        type: integer
      sever_labor_relationship_date:
        description: 26.解除或终止劳动关系时间年月日
        example: "2020-01-02"
        type: string
      sever_labor_relationship_employer:
        description: 25. 双方解除或终止劳动关系的原因
        type: boolean
      sever_labor_relationship_employer_reason:
        type: string
      sever_labor_relationship_labor:
        type: boolean
      sever_labor_relationship_labor_reason:
        type: string
      should_rest:
        description: 应休
        type: integer
      social_insurance:
        description: |-
          12.办理社会保险及险种
          12.1 是否进行社会保险
        type: boolean
      social_insurance_payment_time:
        description: 12.3 社会保险缴险时间
        items:
          type: string
        type: array
      social_insurance_type:
        description: 12.2 社会保险险种
        type: integer
      statutory_holidays:
        description: 法定节假日加班小时
        example: 10
        type: number
      statutory_rest:
        description: 法定休息日加班小时
        example: 10
        type: number
      unpaid_wages:
        description: |-
          11. 欠发工资及加班费数额
          11.1 欠发工资数
        type: number
      wage:
        description: |-
          9. 实发月工资数及工资构成、发放形式、发放周期
          9.1 月工资数
        type: number
      wage_component:
        description: 9.2 工资构成
        type: string
      work_related_treatment_gsylbz:
        description: 17.9. 一次性工伤医疗补助金
        type: number
      work_related_treatment_hsbz:
        description: 17.3 住院期间伙食补助
        type: number
      work_related_treatment_jt:
        description: 17.4 交通费
        type: number
      work_related_treatment_jzaz:
        description: 17.2 假肢安装费
        type: number
      work_related_treatment_other:
        description: 17.11. 其他
        type: number
      work_related_treatment_ph:
        description: 17.5 陪护费
        type: number
      work_related_treatment_scbz:
        description: 17.8 一次性伤残补助金
        type: number
      work_related_treatment_scjt:
        description: 17.7 伤残津贴
        type: number
      work_related_treatment_scjybz:
        description: 17.10. 一次性伤残就业补助金
        type: number
      work_related_treatment_shhl:
        description: 17.6 生活护理费
        type: number
      work_related_treatment_ylf:
        description: |-
          17.需支付的工伤待遇项目及数额
          17.1 医疗费
        type: number
      work_year:
        description: 21. 劳动者在本单位工作年限
        type: integer
    required:
    - arbitration_time
    - hire_date
    - main
    - not_take_days
    - parties_dispute_time
    - payment_cycle
    - payment_type
    - real_rest
    - should_rest
    - wage
    type: object
  vo.LoginResult:
    properties:
      expire:
        type: string
      message:
        example: unauthorized
        type: string
      refresh_url:
        example: /api/auth/refreshToken
        type: string
      status:
        example: 401
        type: integer
      timestamp:
        example: "2048-05-06 12:34:56"
        type: string
      token:
        example: asdsadasdasdasd
        type: string
    type: object
  vo.UserData:
    properties:
      claims:
        $ref: '#/definitions/jwtmodel.UserClaims'
        type: object
      message:
        example: unauthorized
        type: string
      profile:
        $ref: '#/definitions/models.UserProfile'
        type: object
      status:
        example: 401
        type: integer
      timestamp:
        example: "2048-05-06 12:34:56"
        type: string
      user:
        $ref: '#/definitions/models.User'
        type: object
    type: object
  vo.UserUpdateInfo:
    properties:
      email:
        example: hafrans@163.com
        type: string
      phone:
        example: test@gov.cn
        type: string
    required:
    - email
    - phone
    type: object
info:
  contact:
    email: lvzh@hafrans.com
    name: Chuuka Ro (Hafrans)
    url: http://hafrans.com/support
  description: 岚山区劳动争议调解区块链平台，后台采用golang开发，使用gin + gorm + gorbac + jwt开发
  license: {}
  termsOfService: http://hafrans.com
  title: 岚山区劳动争议调解区块链平台
  version: 0.0.2
paths:
  /api/auth/captcha/:id:
    get:
      description: 获取验证码
      parameters:
      - description: 验证码id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 同时返回验证码的时间戳、base64化图片、验证码challenge指令
          schema:
            $ref: '#/definitions/vo.CommonData'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 获得验证码
      tags:
      - captcha
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: 用户登录并获得token以及失效日期
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 验证码
        in: body
        name: captcha_code
        required: true
        schema:
          type: string
      - description: 验证码时间戳 （2006-01-02 15:04:05）
        in: body
        name: captcha_time
        required: true
        schema:
          type: string
      - description: 验证码挑战指令
        in: body
        name: captcha_challenge
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.LoginResult'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 用户登录
      tags:
      - user
  /api/v1/:
    get:
      consumes:
      - multipart/form-data
      description: 上传资源 ，支持 pdf,doc,docx,pdfx,txt,mp3,zip,jpg,gif,jpeg,png格式
      parameters:
      - description: 要上传的资源
        in: query
        name: file
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.Common'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 上传资源
      tags:
      - utils
  /api/v1/case/create:
    get:
      consumes:
      - application/json
      description: 由申请人填写创建新调解案件
      parameters:
      - description: 提交表单
        in: body
        name: case
        required: true
        schema:
          $ref: '#/definitions/vo.CaseFirstSubmitForm'
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/vo.CommonData'
        "401":
          description: 没有认证
          schema:
            $ref: '#/definitions/vo.Common'
        "422":
          description: 绑定失败
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 创建新调解案件
      tags:
      - case
  /api/v1/category:
    get:
      description: 获取所有类型
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.CommonData'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 获得所有类型
      tags:
      - category
      - case
  /api/v1/labor/arbitration/:
    get:
      consumes:
      - application/json
      description: 劳动争议案件审判要素表列表
      parameters:
      - description: 页码
        in: query
        name: page
        required: true
        type: number
      - description: 页大小
        in: query
        name: pageSize
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: 正常业务处理
          schema:
            $ref: '#/definitions/vo.CommonData'
        "401":
          description: 未验证
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 获取自己所有的劳动争议案件审判要素表
      tags:
      - labor
  /api/v1/labor/arbitration/:id:
    get:
      consumes:
      - application/json
      description: 劳动争议案件审判要素表获取，非管理员只能看自己的。
      parameters:
      - description: 表单id
        in: path
        name: id
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: 正常业务处理
          schema:
            $ref: '#/definitions/vo.CommonData'
        "401":
          description: 未验证
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 获取指定劳动争议案件审判要素表列表
      tags:
      - labor
  /api/v1/labor/arbitration/create:
    post:
      consumes:
      - application/json
      description: 劳动争议案件审判要素表新建
      parameters:
      - description: 表单
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/vo.LaborArbitrationForm'
      produces:
      - application/json
      responses:
        "200":
          description: 正常业务处理
          schema:
            $ref: '#/definitions/vo.CommonData'
        "401":
          description: 未验证
          schema:
            $ref: '#/definitions/vo.Common'
        "422":
          description: 表单绑定失败
          schema:
            $ref: '#/definitions/vo.Common'
        "500":
          description: 表单绑定失败
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 创建劳动争议案件审判要素表
      tags:
      - labor
  /api/v1/labor/arbitration_instructor:
    post:
      description: 获取劳动争议表单模板
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.CommonData'
        "401":
          description: 未验证
          schema:
            $ref: '#/definitions/vo.Common'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 获取劳动争议表单模板
      tags:
      - test
      - labor
  /api/v1/user/info:
    get:
      description: 获取用户信息
      produces:
      - application/json
      responses:
        "200":
          description: 正常业务处理
          schema:
            $ref: '#/definitions/vo.UserData'
        "401":
          description: 未验证
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 获取用户信息
      tags:
      - user
  /api/v1/user/reset_password:
    post:
      consumes:
      - application/json
      description: 用户自行修改密码
      parameters:
      - description: 原始密码
        in: body
        name: old_password
        required: true
        schema:
          type: string
      - description: 新密码，最小长度3 最大长度20
        in: body
        name: new_password
        required: true
        schema:
          type: string
      - description: 重新输入密码
        in: body
        name: confirm_password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 正常业务处理
          schema:
            $ref: '#/definitions/vo.Common'
        "401":
          description: 未验证
          schema:
            $ref: '#/definitions/vo.Common'
        "422":
          description: 表单绑定失败
          schema:
            $ref: '#/definitions/vo.Common'
        "500":
          description: 表单绑定失败
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 修改密码
      tags:
      - user
  /api/v1/user/update_info:
    post:
      consumes:
      - application/json
      description: 修改用户邮箱和密码
      parameters:
      - description: 请求
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/vo.UserUpdateInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 正常业务处理
          schema:
            $ref: '#/definitions/vo.Common'
        "401":
          description: 未验证
          schema:
            $ref: '#/definitions/vo.Common'
        "422":
          description: 表单绑定失败
          schema:
            $ref: '#/definitions/vo.Common'
        "500":
          description: 表单绑定失败
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 修改用户基础信息（邮箱和密码）
      tags:
      - user
swagger: "2.0"
