definitions:
  vo.Common:
    properties:
      message:
        example: unauthorized
        type: string
      status:
        example: 401
        type: integer
      timestamp:
        example: "2048-05-06 12:34:56"
        type: string
    type: object
  vo.LoginResult:
    properties:
      expire:
        type: string
      message:
        example: unauthorized
        type: string
      refresh_url:
        example: /api/auth/refreshToken
        type: string
      status:
        example: 401
        type: integer
      timestamp:
        example: "2048-05-06 12:34:56"
        type: string
      token:
        example: asdsadasdasdasd
        type: string
    type: object
info:
  contact:
    email: lvzh@hafrans.com
    name: Chuuka Ro (Hafrans)
    url: http://hafrans.com/support
  description: 岚山区劳动争议调解区块链平台，后台采用golang开发，使用gin + gorm + gorbac + jwt开发
  license: {}
  termsOfService: http://hafrans.com
  title: 岚山区劳动争议调解区块链平台
  version: 0.0.2
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: 用户登录并获得token以及失效日期
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: 验证码
        in: body
        name: captcha_code
        required: true
        schema:
          type: string
      - description: 验证码时间戳 （2006-01-02 15:04:05）
        in: body
        name: captcha_time
        required: true
        schema:
          type: string
      - description: 验证码挑战指令
        in: body
        name: captcha_challenge
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.LoginResult'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vo.Common'
      summary: 用户登录
  /api/v1/:
    get:
      consumes:
      - application/json
      description: 测试在登录情况下是否可以访问
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/vo.Common'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/vo.Common'
      summary: ApiIndex
      tags:
      - test
      - index
  /api/v1/tags:
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增文章标签
swagger: "2.0"
